package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	models_graph "github.com/rusneustroevkz/http-server/graph/models"
)

// Update is the resolver for the update field.
func (r *mutationResolver) Update(ctx context.Context) (*models_graph.ProductResponse, error) {
	panic(fmt.Errorf("not implemented: Update - update"))
}

// Get is the resolver for the get field.
func (r *queryResolver) Get(ctx context.Context) (*models_graph.ProductResponse, error) {
	panic(fmt.Errorf("not implemented: Get - get"))
}
