// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pets.proto

package petspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Pets_SayHello_FullMethodName = "/petspb.Pets/SayHello"
)

// PetsClient is the client API for Pets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PetsClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type petsClient struct {
	cc grpc.ClientConnInterface
}

func NewPetsClient(cc grpc.ClientConnInterface) PetsClient {
	return &petsClient{cc}
}

func (c *petsClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Pets_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PetsServer is the server API for Pets service.
// All implementations must embed UnimplementedPetsServer
// for forward compatibility
type PetsServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedPetsServer()
}

// UnimplementedPetsServer must be embedded to have forward compatible implementations.
type UnimplementedPetsServer struct {
}

func (UnimplementedPetsServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedPetsServer) mustEmbedUnimplementedPetsServer() {}

// UnsafePetsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PetsServer will
// result in compilation errors.
type UnsafePetsServer interface {
	mustEmbedUnimplementedPetsServer()
}

func RegisterPetsServer(s grpc.ServiceRegistrar, srv PetsServer) {
	s.RegisterService(&Pets_ServiceDesc, srv)
}

func _Pets_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetsServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pets_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetsServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pets_ServiceDesc is the grpc.ServiceDesc for Pets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "petspb.Pets",
	HandlerType: (*PetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Pets_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pets.proto",
}
