// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models_graph

type Mutation struct {
}

type ProductRequest struct {
	ID *int `json:"id,omitempty"`
}

type ProductResponse struct {
	ID *int `json:"id,omitempty"`
}

type Query struct {
}
